# Generated by Django 4.1.1 on 2022-09-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('slug', models.TextField(unique=b'I01\n')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('text', models.TextField(blank=b'I01\n')),
                ('rank', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('', 'Active')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=b'I01\n', max_length=200)),
                ('slug', models.TextField(unique=b'I01\n')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categories')),
            ],
        ),
    ]
