# Generated by Django 4.1.1 on 2022-09-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_brand_review_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('profession', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
    ]
