# Generated by Django 4.1.1 on 2022-09-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
