# Generated by Django 4.1.1 on 2022-09-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Subcategory',
            new_name='subcategory',
        ),
    ]
