# Generated by Django 4.1.1 on 2022-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
